name: blockfrost
version: 1.1.0-dev.1
description: Dart OpenAPI API blockfrost client based on Dio 4.x
homepage: https://github.com/reaster/blockfrost_api

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^5.1.1
  one_of: ">=1.5.0 <2.0.0"
  one_of_serializer: ">=1.5.0 <2.0.0"
  built_value: ">=8.4.0 <9.0.0"
  built_collection: ">=5.1.1 <6.0.0"

dev_dependencies:
  built_value_generator: ">=8.4.0 <9.0.0"
  build_runner: any
  test: ^1.16.0
